version: "3"
services:
  seata:
    container_name: seata
    image: seataio/seata-server
    ports:
      - "8091:8091"
    volumes:
      - ./seata/registry.conf:/root/registry.conf
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
      - SEATA_CONFIG_NAME=/root/registry
    depends_on:
      - nacos

  product-svc:
    container_name: product-svc
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        - APP=product-svc
    environment:
      - APP=product-svc
      - CONF_PROVIDER_FILE_PATH=/build/product-svc/profiles/dev/server.yml
      - APP_LOG_CONF_FILE=/build/product-svc/profiles/dev/log.yml
      - SEATA_CONF_FILE=/build/product-svc/profiles/dev/seata.yml
    depends_on:
      - mysql
      - seata

  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./logs:/home/nacos/logs
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./logs:/var/log/grafana
    ports:
      - 3000:3000
